6.5
htmlacademy-ecmascript/118601-big-trip-16 pull request #12
Opened 2021-12-26 16:13 UTC by ammodit-p

2021-12-27 10:20 UTC, maks88sgt requested changes

2021-12-27 10:20 UTC, maks88sgt commented on src/utils/dayjs.js
> +export const dateToDayJs = (date) => dayjs(date);
По-моему это лишний уровень абстракции. Ведь сам по себе вызов dayjs вернет тоже самое.

2021-12-27 10:20 UTC, maks88sgt commented on src/view/editable-point-view.js
> +    static parseDataTiPoint = (data) => {
Наверное просто очепятка
```suggestion
    static parseDataToPoint = (data) => {
```

2021-12-27 10:20 UTC, maks88sgt commented on src/view/editable-point-view.js
> +      const startDate = dateToDayJs(date);
```suggestion
      const startDate = dayjs(date);
```

2021-12-27 10:20 UTC, maks88sgt commented on src/view/editable-point-view.js
> +      const endDate = dateToDayJs(date);
```suggestion
      const endDate = dayjs(date);
```

2021-12-27 10:20 UTC, maks88sgt commented on src/view/editable-point-view.js
>  }
С этой вьюшкой есть проблемы с офферами. Проверь работу с this.#selectedOffers полем.

2021-12-30 14:45 UTC, ammodit-p commented on src/view/editable-point-view.js
>  }
плохо писать код в уставшем состоянии)
я поправила

2021-12-30 15:06 UTC, maks88sgt approved these changes

2021-12-30 15:06 UTC, merged