1.9 первые компоненты
htmlacademy-ecmascript/118601-big-trip-16 pull request #5
Opened 2021-11-23 21:21 UTC by ammodit-p

+ поправила команды сборки и старта, неудобно работать

2021-11-24 08:31 UTC, maks88sgt requested changes

2021-11-24 08:31 UTC, maks88sgt commented on src/main.js
> +import {createPoint} from './view/point-view';
Проверь, пожалуйста, соответсвие названий функций и названий файлов. Я в принципе за любой подход, который будет соответствовать единому стилю и ТЗ.

2021-11-24 08:31 UTC, maks88sgt commented on package.json
> +    "server": "webpack serve --open --mode=development"
Давай вернем все в исходное. Согласен, что это может быть удобнее, но у нас есть ТЗ.

2021-11-24 12:22 UTC, ammodit-p commented on src/main.js
> +import {createPoint} from './view/point-view';
я делала по тому как показали тут: https://github.com/htmlacademy-ecmascript/taskmanager-16
у них тоже название файла с -view, а функции с глаголом create

согласна, что название файла и функции должно совпадать, но я не знаю как конкретно сейчас нужно

2021-11-24 12:23 UTC, ammodit-p commented on src/main.js
> +import {createPoint} from './view/point-view';
плюс, у них в тексте задания вот это написано:
`именуйте файлы как существительные (да, мы пока осознанно нарушаем критерий Б27);`

2021-11-25 08:15 UTC, maks88sgt approved these changes

2021-11-25 08:16 UTC, merged