2.10 моковые данные
htmlacademy-ecmascript/118601-big-trip-16 pull request #6
Opened 2021-11-28 16:21 UTC by ammodit-p

2021-11-28 17:32 UTC, maks88sgt requested changes

2021-11-28 17:32 UTC, maks88sgt commented on src/conts.js
> +};
Посмотри критерий Б.7 https://up.htmlacademy.ru/ecmascript/16/criteries#b7. И чекни плиз это далее по ПРу

2021-11-28 17:32 UTC, maks88sgt commented on src/mock/points.js
> +    end,
Давай заменим это на startDate, endDate, потому что когда встречаешь это в коде в других местах, не совсем очевидно о чем это о дате, точке маршрута или еще что.

2021-11-28 17:32 UTC, maks88sgt commented on src/view/trip-info-title-view.js
> +  };
Давай заменим это на switch/case это будет более гибкое решение, которое легко будет изменяться при необходимости

2021-11-29 19:31 UTC, ammodit-p commented on src/conts.js
> +};
название перечислений сделаю с большой буквы.
нет возражений против того что в названии используется enum? в js все-таки нет втроенных enum'ов, это имитация

2021-11-29 21:31 UTC, maks88sgt approved these changes

2021-11-29 21:31 UTC, maks88sgt commented on src/conts.js
> +};
Нет, я за понятный код. У нас нет типизации и чего-то такого, поэтому это может быть полезно.

2021-11-29 21:31 UTC, merged